<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd347824856e18d789a8dc0f2f1b05509
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'D' => 
        array (
            'Detection' => 
            array (
                0 => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/namespaced',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Mobile_Detect' => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/Mobile_Detect.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd347824856e18d789a8dc0f2f1b05509::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd347824856e18d789a8dc0f2f1b05509::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitd347824856e18d789a8dc0f2f1b05509::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitd347824856e18d789a8dc0f2f1b05509::$classMap;

        }, null, ClassLoader::class);
    }
}
